version: "2"
linters:
  enable:
    - copyloopvar
    - errname
    - errorlint
    - exhaustive
    - goconst
    - gocritic
    - godot
    - goprintffuncname
    - iface
    - intrange
    - makezero
    - misspell
    - nilerr
    - prealloc
    - revive
    - thelper
    - unconvert
    - unparam
    - usestdlibvars
    - wastedassign
  exclusions:
    presets:
      - std-error-handling
    rules:
      - linters:
          - revive
        text: "unused-parameter"
  settings:
    gocritic:
      enabled-tags:
        - diagnostic
        - performance
        - style
      disabled-checks:
        - hugeParam
formatters:
  enable:
    - goimports
